SELECT  p.PRODUCT_ID
       ,p.PRODUCT_NAME
       ,p.price*SUM(amount) AS TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN FOOD_ORDER o
ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE PRODUCE_DATE like '2022-05%'
GROUP BY  PRODUCT_ID
ORDER BY TOTAL_SALES desc
         ,O.PRODUCT_ID;