SELECT  YEAR(S.SALES_DATE)        AS YEAR
       ,MONTH(S.SALES_DATE)       AS MONTH
       ,U.GENDER                  AS GENDER
       ,COUNT(distinct U.USER_ID) AS USERS
FROM USER_INFO U
JOIN ONLINE_SALE S
ON U.USER_ID = S.USER_ID
GROUP BY  YEAR
         ,MONTH
         ,GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER