SELECT  WAREHOUSE_ID
       ,WAREHOUSE_NAME
       ,ADDRESS
       ,ifnull (FREEZER_YN , 'N') AS FREEZER_YN
       -- if (FREEZER_YN is null ,'N',FREEZER_YN) AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS like '경기%'
ORDER BY WAREHOUSE_ID